# Advent of Code 2021
## [Day 13: Transparent Origami](https://adventofcode.com/2021/day/13)

#### Load Data

In [1]:
import numpy as np

import html
html_formatter = get_ipython().display_formatter.formatters['text/html']

def ndarray_to_html(a):
    return "<pre>{}</pre>".format(html.escape(str(a.astype(int))))

html_formatter.for_type(np.ndarray, ndarray_to_html)

In [2]:
import aocd
input_data = aocd.get_data(day=13, year=2021).split('\n')
input_data[-18:-8]

['1218,274',
 '736,761',
 '641,536',
 '152,142',
 '376,373',
 '',
 'fold along x=655',
 'fold along y=447',
 'fold along x=327',
 'fold along y=223']

In [3]:
test_data = [
    '6,10',
    '0,14',
    '9,10',
    '0,3',
    '10,4',
    '4,11',
    '6,0',
    '6,12',
    '4,1',
    '0,13',
    '10,12',
    '3,4',
    '3,0',
    '8,4',
    '1,10',
    '2,14',
    '8,10',
    '9,0',
    '',
    'fold along y=7',
    'fold along x=5'
]

In [4]:
def parse_data(data):
    a = np.zeros((2000,2000), dtype=bool)
    coords = []
    folds = []
    
    for line in data:
        if line.startswith('fold along '):
            axis, value = line[11:].split('=')
            folds.append((axis, int(value)))
        elif line:
            x, y = map(int, line.split(','))
            a[x, y] = True
            coords.append((x, y))
    return np.array(coords), folds

coords, folds = parse_data(test_data)
coords, folds

(array([[ 6, 10],
        [ 0, 14],
        [ 9, 10],
        [ 0,  3],
        [10,  4],
        [ 4, 11],
        [ 6,  0],
        [ 6, 12],
        [ 4,  1],
        [ 0, 13],
        [10, 12],
        [ 3,  4],
        [ 3,  0],
        [ 8,  4],
        [ 1, 10],
        [ 2, 14],
        [ 8, 10],
        [ 9,  0]]),
 [('y', 7), ('x', 5)])

### Part 1

In [5]:
def coords_to_grid(coords):
    X = coords.T[0]
    x0 = X.min()
    w = X.max() - X.min() + 1
    Y = coords.T[1]
    y0 = Y.min()
    h = Y.max() - Y.min() + 1
    grid = np.zeros((h, w), dtype=bool)
    for (x, y) in coords:
        grid[y - y0, x - x0] = True
    return grid
coords_to_grid(coords)

array([[False, False, False,  True, False, False,  True, False, False,
         True, False],
       [False, False, False, False,  True, False, False, False, False,
        False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False],
       [ True, False, False, False, False, False, False, False, False,
        False, False],
       [False, False, False,  True, False, False, False, False,  True,
        False,  True],
       [False, False, False, False, False, False, False, False, False,
        False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False],
       [False,  True, False, False, False, False,  True, False,  True,
         True, False],
       [False, False, False, False,  True, False, False, False, False,
        False, False],
       [False, False, False, False, False, False,  True, False, False,
        False,  True],
       [ True, False, False, False, False, False, False, False, False,
        False, False],
       [ True, False,  True, False, False, False, False, False, False,
        False, False]])

In [6]:
def apply_fold(coords, fold):
    axes = {
        'x': 0,
        'y': 1
    }
    axis = axes[fold[0]]
    value = fold[1]
    
    coords_T = coords.T.copy()
    
    selected = coords_T[axis] > value
    coords_T[axis][selected] = value - (coords_T[axis][selected] - value)
    
    return coords_T.T

apply_fold(coords, folds[1])

array([[ 4, 10],
       [ 0, 14],
       [ 1, 10],
       [ 0,  3],
       [ 0,  4],
       [ 4, 11],
       [ 4,  0],
       [ 4, 12],
       [ 4,  1],
       [ 0, 13],
       [ 0, 12],
       [ 3,  4],
       [ 3,  0],
       [ 2,  4],
       [ 1, 10],
       [ 2, 14],
       [ 2, 10],
       [ 1,  0]])

In [7]:
folded_coords = coords
for fold in folds:
    folded_coords = apply_fold(folded_coords, fold)
folded_coords

array([[4, 4],
       [0, 0],
       [1, 4],
       [0, 3],
       [0, 4],
       [4, 3],
       [4, 0],
       [4, 2],
       [4, 1],
       [0, 1],
       [0, 2],
       [3, 4],
       [3, 0],
       [2, 4],
       [1, 4],
       [2, 0],
       [2, 4],
       [1, 0]])

#### Part 1 Answer
**How many dots are visible after completing just the first fold instruction on your transparent paper?**

In [8]:
coords, folds = parse_data(input_data)
coords_to_grid(apply_fold(coords, folds[0])).sum()

850

### Part 2

#### Part 2 Answer
Finish folding the transparent paper according to the instructions. The manual says the code is always **eight capital letters.**

**What code do you use to activate the infrared thermal imaging camera system?**

In [9]:
coords, folds = parse_data(input_data)
folded_coords = coords
for fold in folds:
    folded_coords = apply_fold(folded_coords, fold)
code = coords_to_grid(folded_coords)
code

array([[False,  True,  True, False, False,  True, False, False,  True,
        False, False,  True,  True, False, False, False,  True,  True,
        False, False,  True,  True,  True, False, False, False,  True,
         True, False, False, False,  True,  True, False, False,  True,
        False, False,  True],
       [ True, False, False,  True, False,  True, False, False,  True,
        False,  True, False, False,  True, False,  True, False, False,
         True, False,  True, False, False,  True, False,  True, False,
        False,  True, False,  True, False, False,  True, False,  True,
        False, False,  True],
       [ True, False, False,  True, False,  True,  True,  True,  True,
        False,  True, False, False, False, False,  True, False, False,
        False, False,  True, False, False,  True, False,  True, False,
        False, False, False,  True, False, False,  True, False,  True,
        False, False,  True],
       [ True,  True,  True,  True, False,  True, False, False,  True,
        False,  True, False,  True,  True, False,  True, False, False,
        False, False,  True,  True,  True, False, False,  True, False,
         True,  True, False,  True,  True,  True,  True, False,  True,
        False, False,  True],
       [ True, False, False,  True, False,  True, False, False,  True,
        False,  True, False, False,  True, False,  True, False, False,
         True, False,  True, False, False, False, False,  True, False,
        False,  True, False,  True, False, False,  True, False,  True,
        False, False,  True],
       [ True, False, False,  True, False,  True, False, False,  True,
        False, False,  True,  True,  True, False, False,  True,  True,
        False, False,  True, False, False, False, False, False,  True,
         True,  True, False,  True, False, False,  True, False, False,
         True,  True, False]])

In [10]:
import PIL.Image
from io import BytesIO
import IPython.display
def int_array_to_image(a, fmt='png'):
    a = 240 - (a/a.max() * 224).astype(np.uint8)
    f = BytesIO()
    PIL.Image.fromarray(a).save(f, fmt)
    return IPython.display.Image(data=f.getvalue())
def double_bitmap(a):
    (h, w) = a.shape
    return np.tile(a.reshape((-1, 1)), 2).reshape((h, w*2))
def quad_bitmap(a):
    return double_bitmap(double_bitmap(a).T).T


In [11]:
int_array_to_image(quad_bitmap(quad_bitmap(code)))