# Advent of Code 2019
## [Day 2: 1202 Program Alarm](https://adventofcode.com/2019/day/2)

#### Load Data

In [1]:
import numpy as np

In [2]:
import aocd
input_data = aocd.get_data(year=2019, day=2)
input_program = np.array(input_data.split(','), dtype=int)
input_program

array([  1,   0,   0,   3,   1,   1,   2,   3,   1,   3,   4,   3,   1,
         5,   0,   3,   2,  10,   1,  19,   1,   5,  19,  23,   1,  23,
         5,  27,   2,  27,  10,  31,   1,   5,  31,  35,   2,  35,   6,
        39,   1,   6,  39,  43,   2,  13,  43,  47,   2,   9,  47,  51,
         1,   6,  51,  55,   1,  55,   9,  59,   2,   6,  59,  63,   1,
         5,  63,  67,   2,  67,  13,  71,   1,   9,  71,  75,   1,  75,
         9,  79,   2,  79,  10,  83,   1,   6,  83,  87,   1,   5,  87,
        91,   1,   6,  91,  95,   1,  95,  13,  99,   1,  10,  99, 103,
         2,   6, 103, 107,   1, 107,   5, 111,   1, 111,  13, 115,   1,
       115,  13, 119,   1,  13, 119, 123,   2, 123,  13, 127,   1, 127,
         6, 131,   1, 131,   9, 135,   1,   5, 135, 139,   2, 139,   6,
       143,   2,   6, 143, 147,   1,   5, 147, 151,   1, 151,   2, 155,
         1,   9, 155,   0,  99,   2,  14,   0,   0])

In [3]:
test_program = np.array([1,9,10,3,2,3,11,0,99,30,40,50])
test_program

array([ 1,  9, 10,  3,  2,  3, 11,  0, 99, 30, 40, 50])

### Part 1

In [4]:
def interpret_intcode(program):
    program = program.copy()
    pc = 0
    while True:
        opcode, lhs, rhs, result = program[pc:pc+4]
        print(opcode, lhs, rhs, result)
        if opcode == 1:
            program[result] = program[lhs] + program[rhs]
        elif opcode == 2:
            program[result] = program[lhs] * program[rhs]
        elif opcode == 99:
            return program
        print(program)
        pc += 4
        
interpret_intcode(test_program)

1 9 10 3
[ 1  9 10 70  2  3 11  0 99 30 40 50]
2 3 11 0
[3500    9   10   70    2    3   11    0   99   30   40   50]
99 30 40 50


array([3500,    9,   10,   70,    2,    3,   11,    0,   99,   30,   40,
         50])

In [5]:
def format_intcode(program):
    printout = ''
    pc = 0
    while pc < len(program):
        opcode = program[pc]
        printout += f"{pc: 4d} "
        if opcode == 1:
            lhs, rhs, result = program[pc+1:pc+4]
            printout += f"ADD  {lhs} {rhs} {result}\n"
            pc += 4
        elif opcode == 2:
            lhs, rhs, result = program[pc+1:pc+4]
            printout += f"MUL  {lhs} {rhs} {result}\n"
            pc += 4
        elif opcode == 99:
            printout += f"HALT\n"
            pc += 1
            next
        else:
            printout += str(program[pc:])[1:-1]
            pc = len(program)
    return printout

print(format_intcode(test_program))

   0 ADD  9 10 3
   4 MUL  3 11 0
   8 HALT
   9 30 40 50


In [6]:
len(test_program)

12

In [7]:
def intcode(program, printout=False):
    program = np.array(program)
    pc = 0
    while pc < len(program):
        opcode = program[pc]
        if opcode == 1:
            lhs, rhs, result = program[pc+1:pc+4]
            if printout:
                print(f"{pc: 6d}: ADD  {lhs} + {rhs} -> {result}")
            program[result] = program[lhs] + program[rhs]
            pc += 4
        elif opcode == 2:
            lhs, rhs, result = program[pc+1:pc+4]
            if printout:
                print(f"{pc: 6d}: MUL  {lhs} * {rhs} -> {result}")
            program[result] = program[lhs] * program[rhs]
            pc += 4
        elif opcode == 99:
            if printout:
                print(f"{pc: 6d}: HALT")
            return program
        else:
            if printout:
                print(f"{pc: 6d}: DATA {str(program[pc:])[1:-1]}")
            pc = len(program)
    return program

intcode(test_program, printout=True)

     0: ADD  9 + 10 -> 3
     4: MUL  3 * 11 -> 0
     8: HALT


array([3500,    9,   10,   70,    2,    3,   11,    0,   99,   30,   40,
         50])

In [8]:
intcode([1,0,0,0,99], printout=True)

     0: ADD  0 + 0 -> 0
     4: HALT


array([ 2,  0,  0,  0, 99])

In [9]:
intcode([2,3,0,3,99], printout=True)

     0: MUL  3 * 0 -> 3
     4: HALT


array([ 2,  3,  0,  6, 99])

In [10]:
intcode([2,4,4,5,99,0], printout=True)

     0: MUL  4 * 4 -> 5
     4: HALT


array([   2,    4,    4,    5,   99, 9801])

In [11]:
intcode([1,1,1,4,99,5,6,0,99], printout=True)

     0: ADD  1 + 1 -> 4
     4: MUL  5 * 6 -> 0
     8: HALT


array([30,  1,  1,  4,  2,  5,  6,  0, 99])

In [12]:
intcode(input_program)

array([490668,      0,      0,      2,      1,      1,      2,      3,
            1,      3,      4,      3,      1,      5,      0,      3,
            2,     10,      1,      0,      1,      5,     19,      1,
            1,     23,      5,      2,      2,     27,     10,      8,
            1,      5,     31,      9,      2,     35,      6,     18,
            1,      6,     39,     20,      2,     13,     43,    100,
            2,      9,     47,    300,      1,      6,     51,    302,
            1,     55,      9,    305,      2,      6,     59,    610,
            1,      5,     63,    611,      2,     67,     13,   3055,
            1,      9,     71,   3058,      1,     75,      9,   3061,
            2,     79,     10,  12244,      1,      6,     83,  12246,
            1,      5,     87,  12247,      1,      6,     91,  12249,
            1,     95,     13,  12254,      1,     10,     99,  12258,
            2,      6,    103,  24516,      1,    107,      5,  24517,
      

#### Part 1 Answer
Once you have a working computer, the first step is to restore the gravity assist program (your puzzle input) to the "1202 program alarm" state it had just before the last computer caught fire. To do this, **before running the program,** replace position 1 with the value 12 and replace position 2 with the value 2.  
**What value is left at position 0 after the program halts?**

In [13]:
fixed_program = input_program.copy()
fixed_program[1] = 12
fixed_program[2] = 2
intcode(fixed_program)[0]

9706670

### Part 2

In [14]:
def intcode_nv(program, noun, verb):
    program = np.array(program)
    program[1] = noun
    program[2] = verb
    return intcode(program)

intcode_nv(input_program, 12, 2)[0]

9706670

#### Part 2 Answer
Find the input **noun** and **verb** that cause the program to produce the output 19690720.  
**What is 100 * noun + verb?** (For example, if noun=12 and verb=2, the answer would be 1202.)

In [15]:
def find_nv(program, target):
    for noun in range(100):
        for verb in range(100):
            if intcode_nv(program, noun, verb)[0] == target:
                return noun, verb

noun, verb = find_nv(input_program, 19690720)
100 * noun + verb

2552