# Advent of Code 2021
## Day 3

In [1]:
import numpy as np

### Part 1

In [2]:
def parse_line(line):
    return list(line.decode('utf-8'))

report = np.loadtxt('input.txt', dtype='uint8', converters={0:parse_line})
report

array([[0, 1, 1, ..., 1, 1, 0],
       [0, 1, 0, ..., 1, 0, 1],
       [1, 0, 0, ..., 1, 1, 0],
       ...,
       [0, 1, 1, ..., 1, 1, 0],
       [1, 1, 1, ..., 0, 0, 1],
       [0, 0, 1, ..., 0, 0, 0]], dtype=uint8)

In [3]:
gamma_bits = (report.mean(axis=0) > 0.5).astype(int)
gamma_bits

array([0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0])

In [4]:
def bits_to_int(bits):
    bit_string = ''.join(map(str, list(bits)))
    value = int(bit_string, base=2)
    return value

bits_to_int(gamma_bits)

1836

In [5]:
def bits_to_int(bits):
    bits_32 = np.concatenate([[0] * (32 - len(bits)), bits])
    value = np.packbits(bits_32, bitorder='big')[::-1].copy().view('int32')[0]
    return value

gamma_rate = bits_to_int(gamma_bits)
gamma_rate

1836

In [6]:
epsilon_bits = 1 - gamma_bits
epsilon_bits

array([1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1])

In [7]:
epsilon_rate = bits_to_int(epsilon_bits)
epsilon_rate

2259

#### Part 1 Answer
The power consumption can then be found by multiplying the gamma rate by the epsilon rate.

What is the power consumption of the submarine?

In [8]:
gamma_rate * epsilon_rate

4147524

### Part 2

In [9]:
def find_rating(selected_rows, least_common=False):
    for i in range(selected_rows.shape[1]):
        if len(selected_rows) == 1:
            break
        bit_criterion = int(selected_rows[:, i].mean() >= 0.5) ^ least_common
        matching_rows = selected_rows[:, i] == bit_criterion
        selected_rows = selected_rows[matching_rows]
        # print(f"i: {i}, bit criterion: {bit_criterion}, selected rows: {np.count_nonzero(matching_rows)}")
    return selected_rows[0]

oxygen_rating_bits = find_rating(report, least_common=False)
oxygen_rating_bits

array([0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1], dtype=uint8)

In [10]:
oxygen_rating = bits_to_int(oxygen_rating_bits)
oxygen_rating

1427

In [11]:
co2_rating_bits = find_rating(report, least_common=True)
co2_rating_bits

array([1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0], dtype=uint8)

In [12]:
co2_rating = bits_to_int(co2_rating_bits)
co2_rating

2502

#### Part 2 Answer
The life support rating can be determined by multiplying the oxygen generator rating by the CO2 scrubber rating.

What is the life support rating of the submarine?

In [13]:
oxygen_rating * co2_rating

3570354