# Advent of Code 2021
## [Day 15: Chiton](https://adventofcode.com/2021/day/15)

#### Load Data

In [1]:
import numpy as np

In [2]:
def parse_line(line):
    return np.array(list(line.strip()), dtype=int)
def parse_input(lines):
    return np.array([parse_line(line) for line in lines])

In [3]:
import aocd
input_data = parse_input(aocd.get_data(year=2021, day=15).split('\n'))
input_data

array([[1, 3, 7, ..., 2, 8, 2],
       [1, 2, 1, ..., 9, 6, 1],
       [6, 1, 5, ..., 2, 8, 4],
       ...,
       [6, 4, 4, ..., 2, 7, 9],
       [9, 7, 2, ..., 7, 9, 4],
       [9, 5, 2, ..., 6, 1, 9]])

In [4]:
test_data = parse_input([
    '1163751742',
    '1381373672',
    '2136511328',
    '3694931569',
    '7463417111',
    '1319128137',
    '1359912421',
    '3125421639',
    '1293138521',
    '2311944581'
])
test_data

array([[1, 1, 6, 3, 7, 5, 1, 7, 4, 2],
       [1, 3, 8, 1, 3, 7, 3, 6, 7, 2],
       [2, 1, 3, 6, 5, 1, 1, 3, 2, 8],
       [3, 6, 9, 4, 9, 3, 1, 5, 6, 9],
       [7, 4, 6, 3, 4, 1, 7, 1, 1, 1],
       [1, 3, 1, 9, 1, 2, 8, 1, 3, 7],
       [1, 3, 5, 9, 9, 1, 2, 4, 2, 1],
       [3, 1, 2, 5, 4, 2, 1, 6, 3, 9],
       [1, 2, 9, 3, 1, 3, 8, 5, 2, 1],
       [2, 3, 1, 1, 9, 4, 4, 5, 8, 1]])

### Part 1

In [5]:
from collections import deque

In [6]:
directions = np.array([[ 1,  0], [ 0,  1], [-1,  0], [ 0, -1]])

def safest_path(grid, start):
    best_cost = np.zeros_like(grid, dtype=int)
    best_cost += 99999
    steps = 0
    
    to_visit = deque([(np.array(start), 0)])
    while to_visit:
        #print(to_visit)
        visiting, path_cost = to_visit.popleft()
        y, x = visiting

        #print(f"visiting {visiting} {path_cost} {best_cost[y, x]}")
        if path_cost > best_cost[y, x]:
            continue

        best_cost[y, x] = path_cost
        #print("new good step:", visiting, visit_cost)
        steps += 1
        for d in directions:
            target = visiting + d
            ty, tx = target
            if tx < 0 or ty < 0 or tx >= grid.shape[0] or ty >= grid.shape[1]:
                continue
            next_cost = path_cost + grid[ty, tx]
            #print(f"checking {ty, tx}: cost {next_cost}")
            if next_cost >= best_cost[ty, tx]:
                continue
            #print(f"{next_cost} < {best_cost[ty, tx]}")
            best_cost[ty, tx] = next_cost
            to_visit.append((target, next_cost))
    print(steps)
    return best_cost

safest_path(test_data, [0,0])

105


array([[ 0,  1,  7, 10, 17, 22, 23, 30, 34, 36],
       [ 1,  4, 12, 11, 14, 21, 23, 29, 32, 34],
       [ 3,  4,  7, 13, 18, 19, 20, 23, 25, 33],
       [ 6, 10, 16, 17, 26, 22, 21, 26, 31, 38],
       [13, 14, 20, 20, 24, 23, 28, 27, 28, 29],
       [14, 17, 18, 27, 25, 25, 33, 28, 31, 36],
       [15, 18, 23, 32, 34, 26, 28, 32, 33, 34],
       [18, 19, 21, 26, 30, 28, 29, 35, 36, 43],
       [19, 21, 30, 29, 30, 31, 37, 40, 38, 39],
       [21, 24, 25, 26, 35, 35, 39, 44, 46, 40]])

### Part 1 Answer
**What is the lowest total risk of any path from the top left to the bottom right?**

In [7]:
safest_path(input_data, [0,0])

38125


array([[  0,   3,  10, ..., 336, 344, 346],
       [  1,   3,   4, ..., 345, 350, 347],
       [  7,   4,   9, ..., 336, 344, 348],
       ...,
       [410, 404, 400, ..., 571, 578, 587],
       [415, 406, 399, ..., 577, 586, 590],
       [415, 406, 401, ..., 582, 583, 592]])

### Part 2

In [9]:
np.arange(1,10) % 9 + 1

array([2, 3, 4, 5, 6, 7, 8, 9, 1])

In [10]:
def expand_grid(grid):
    result = grid.copy()
    next_grid = grid.copy()
    for _ in range(4):
        next_grid = next_grid % 9 + 1
        result = np.hstack([result, next_grid])
    
    grid = result
    result = grid.copy()
    next_grid = grid.copy()
    for _ in range(4):
        next_grid = next_grid % 9 + 1
        result = np.vstack([result, next_grid])
    
    return result

test_expand = expand_grid(test_data)
print(test_expand)

[[1 1 6 ... 2 8 6]
 [1 3 8 ... 1 2 6]
 [2 1 3 ... 7 6 3]
 ...
 [7 5 6 ... 5 2 8]
 [5 6 4 ... 4 1 9]
 [6 7 5 ... 4 7 9]]


In [11]:
safest_path(test_expand, [0,0])

3373


array([[  0,   1,   7, ..., 186, 194, 198],
       [  1,   4,  12, ..., 184, 186, 192],
       [  3,   4,   7, ..., 188, 190, 191],
       ...,
       [180, 185, 181, ..., 301, 298, 306],
       [185, 191, 185, ..., 300, 299, 308],
       [191, 197, 190, ..., 299, 306, 315]])

#### Part 2 Answer
Using the full map, **what is the lowest total risk of any path from the top left to the bottom right?**

In [12]:
input_expand = expand_grid(input_data)
safest_path(input_expand, [0,0])

3041989


array([[   0,    3,   10, ..., 1675, 1676, 1682],
       [   1,    3,    4, ..., 1672, 1673, 1678],
       [   7,    4,    9, ..., 1673, 1676, 1684],
       ...,
       [1763, 1762, 1758, ..., 2872, 2878, 2886],
       [1767, 1764, 1764, ..., 2878, 2886, 2889],
       [1771, 1773, 1770, ..., 2883, 2892, 2897]])