# Advent of Code 2021
## Day 7

### Part 1

In [1]:
import numpy as np

In [2]:
import aocd
input_data = aocd.get_data(day=7, year=2021).split('\n')

In [3]:
crabs = np.array(input_data[0].split(','), dtype=int)
print(crabs[:10])

[1101    1   29   67 1102    0    1   65 1008   65]


In [4]:
len(crabs)

1000

In [5]:
test_crabs = np.array([16,1,2,0,4,2,7,1,2,14])
test_crabs

array([16,  1,  2,  0,  4,  2,  7,  1,  2, 14])

In [6]:
np.arange(test_crabs.min(), test_crabs.max() + 1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [7]:
def cost_for_pos(pos, crabs):
    return np.abs(crabs - pos).sum()
    
cost_for_pos(2, test_crabs)

37

In [8]:
def get_all_costs(crabs):
    all_costs = []
    for i in np.arange(crabs.min(), crabs.max() + 1):
        all_costs.append(cost_for_pos(i, crabs))
    return np.array(all_costs)
get_all_costs(test_crabs).min()

37

#### Part 1 Answer
Determine the horizontal position that the crabs can align to using the least fuel possible.  
**How much fuel must they spend to align to that position?**

In [9]:
get_all_costs(crabs).min()

354129

### Part 2

In [10]:
[np.sum(np.arange(i+1)) for i in range(10)]

[0, 1, 3, 6, 10, 15, 21, 28, 36, 45]

In [11]:
def get_more_cost(n):
    return n * (n + 1) // 2
get_more_cost(np.arange(10))

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [12]:
def cost_for_pos_2(pos, crabs):
    return (np.abs(crabs - pos) * (np.abs(crabs - pos) + 1) // 2).sum()
cost_for_pos_2(2, test_crabs)

206

In [13]:
def get_all_costs_2(crabs):
    all_costs = []
    for i in np.arange(crabs.min(), crabs.max()+1):
        all_costs.append(cost_for_pos_2(i, crabs))
    return np.array(all_costs)
get_all_costs_2(test_crabs).min()

168

In [14]:
get_all_costs_2(test_crabs).argmin()

5

In [22]:
get_all_costs_2(crabs).argmin()

494

In [23]:
np.mean(crabs)

494.601

#### Part 2 Answer
Determine the horizontal position that the crabs can align to using the least fuel possible so they can make you an escape route!  
**How much fuel must they spend to align to that position?**

In [15]:
get_all_costs_2(crabs).min()

98905973

-----

### Visualization

In [16]:
import matplotlib
from matplotlib import pyplot as plt

In [17]:
def plot_crabs(crabs):
    all_costs_1 = get_all_costs(crabs)
    crab_costs_1 = all_costs_1[crabs]
    target1 = all_costs_1.argmin()

    all_costs_2 = get_all_costs_2(crabs)
    crab_costs_2 = all_costs_2[crabs]
    target2 = all_costs_2.argmin()

    norm = matplotlib.colors.Normalize(
        vmin=crab_costs_1.min(),
        vmax=crab_costs_2.max()
    )
    
    fig, (ax1, ax2) = plt.subplots(2, 1)
    fig.set_size_inches(12, 10)
    
    y = np.arange(len(crabs))
    fig.suptitle("Crab Submarine Movement Proposal", fontweight='bold')
    
    ax1.set_title('Linear Cost')
    ax1.set_xlim([crabs.min(), crabs.max()])
    ax1.get_yaxis().set_visible(False)
    ax1.scatter(crabs, y, c=crab_costs_1, cmap='rainbow', norm=norm)
    ax1.axvline(x=target1, color='r', linewidth=3)

    ax2.set_title('Increasing Cost')
    ax2.set_xlim([crabs.min(), crabs.max()])
    ax2.get_yaxis().set_visible(False)
    ax2.scatter(crabs, y, c=crab_costs_2, cmap='rainbow', norm=norm)
    ax2.axvline(x=target2, color='r', linewidth=3)

    return fig
    
plot_crabs(crabs).savefig('crabs.svg')
plt.close()

![crabs.svg](crabs.svg)