In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
%config InlineBackend.figure_formats = ['svg']

# Advent of Code 2021
## Day 1

### Part 1

In [2]:
depth = np.loadtxt("input.txt", dtype=int)
depth

array([ 180,  152,  159, ..., 7484, 7488, 7497])

In [3]:
def plot_depth(depth, *args, fig=None, **kwargs):
    if fig:
        ax = fig.axes[0]
    else:
        fig, (ax) = plt.subplots(1)
        ax.invert_yaxis()
    ax.set_ylabel("depth")
    ax.get_xaxis().set_visible(False)

    ax.plot(np.arange(len(depth)), depth, *args, **kwargs)
    ax.legend()
    plt.close(fig)
    return fig

plot_depth(depth, label='sonar reading').savefig('sonar.svg')

**sonar.svg**  
![sonar.svg](sonar.svg)

In [4]:
def count_increases(a):
    return np.count_nonzero(np.diff(a) > 0)

#### Part 1 Answer
How many measurements are larger than the previous measurement?

In [5]:
count_increases(depth)

1529

### Part 2

In [6]:
depth_windows = np.array([
    depth[:-2],
    depth[1:-1],
    depth[2:]
]).T
depth_windows

array([[ 180,  152,  159],
       [ 152,  159,  171],
       [ 159,  171,  178],
       ...,
       [7482, 7483, 7484],
       [7483, 7484, 7488],
       [7484, 7488, 7497]])

In [7]:
window_sums = np.sum(depth_windows, axis=1)
window_sums

array([  491,   482,   508, ..., 22449, 22455, 22469])

In [8]:
plot_depth(window_sums / 3, color='orange', label='moving average').savefig('moving_average.svg')

**moving_average.svg**  
![moving_average.svg](moving_average.svg)

#### Part 2 Answer
How many sums are larger than the previous sum?

In [9]:
count_increases(window_sums)

1567

### Combined Visualization

In [10]:
fig = plot_depth(window_sums / 3, 'o', color='orange', label='moving average')
fig = plot_depth(depth, fig=fig, color='blue', label='sonar reading')
fig.savefig('depth.svg')

**depth.svg**  
![depth.svg](depth.svg)