# Advent of Code 2021
## Day 6

### Part 1

In [1]:
import numpy as np

In [2]:
import aocd
inputs = aocd.get_data(day=6, year=2021).split('\n')

In [3]:
fishes = np.array(inputs[0].split(','), dtype=int)
print(fishes)

[2 3 1 3 4 4 1 5 2 3 1 1 4 5 5 3 5 5 4 1 2 1 1 1 1 1 1 4 1 1 1 4 1 3 1 4 1
 1 4 1 3 4 5 1 1 5 3 4 3 4 1 5 1 3 1 1 1 3 5 3 2 3 1 5 2 2 1 1 4 1 1 2 2 2
 2 3 2 1 2 5 4 1 1 1 5 5 3 1 3 2 2 2 5 1 5 2 4 1 1 3 3 5 2 3 1 2 1 5 1 4 3
 5 2 1 5 3 4 4 5 3 1 2 4 3 4 1 3 1 1 2 5 4 3 5 3 2 1 4 1 4 4 2 3 1 1 2 1 1
 3 3 3 1 1 2 2 1 1 1 5 1 5 1 4 5 1 5 2 4 3 1 1 3 2 2 1 4 3 1 1 1 3 3 3 4 5
 2 3 3 1 3 1 4 1 1 1 2 5 1 4 1 2 4 5 4 1 5 1 5 5 1 5 5 2 5 5 1 4 5 1 1 3 2
 5 5 5 4 3 2 5 4 1 1 2 4 4 1 1 1 3 2 1 1 2 1 2 2 3 4 5 4 1 4 5 1 1 5 5 1 4
 1 4 4 1 5 3 1 4 3 5 3 1 3 1 4 2 4 5 1 4 1 2 4 1 2 5 1 1 5 1 1 3 1 1 2 3 4
 2 4 3 1]


In [4]:
def simulate_fishes(initial_fishes, num_days):
    fishes_history = [initial_fishes]
    for i in range(num_days):
        current_fishes = fishes_history[i]
        next_fishes = current_fishes - 1
        spawns = next_fishes < 0
        num_spawns = spawns.sum()
        next_fishes[spawns] = 6
        new_fishes = np.repeat([8], num_spawns)
        next_fishes = np.concatenate([next_fishes, new_fishes])
        fishes_history.append(next_fishes)
    return fishes_history

simulate_fishes(np.array([3,4,3,1,2]), 18)

[array([3, 4, 3, 1, 2]),
 array([2, 3, 2, 0, 1]),
 array([1, 2, 1, 6, 0, 8]),
 array([0, 1, 0, 5, 6, 7, 8]),
 array([6, 0, 6, 4, 5, 6, 7, 8, 8]),
 array([5, 6, 5, 3, 4, 5, 6, 7, 7, 8]),
 array([4, 5, 4, 2, 3, 4, 5, 6, 6, 7]),
 array([3, 4, 3, 1, 2, 3, 4, 5, 5, 6]),
 array([2, 3, 2, 0, 1, 2, 3, 4, 4, 5]),
 array([1, 2, 1, 6, 0, 1, 2, 3, 3, 4, 8]),
 array([0, 1, 0, 5, 6, 0, 1, 2, 2, 3, 7, 8]),
 array([6, 0, 6, 4, 5, 6, 0, 1, 1, 2, 6, 7, 8, 8, 8]),
 array([5, 6, 5, 3, 4, 5, 6, 0, 0, 1, 5, 6, 7, 7, 7, 8, 8]),
 array([4, 5, 4, 2, 3, 4, 5, 6, 6, 0, 4, 5, 6, 6, 6, 7, 7, 8, 8]),
 array([3, 4, 3, 1, 2, 3, 4, 5, 5, 6, 3, 4, 5, 5, 5, 6, 6, 7, 7, 8]),
 array([2, 3, 2, 0, 1, 2, 3, 4, 4, 5, 2, 3, 4, 4, 4, 5, 5, 6, 6, 7]),
 array([1, 2, 1, 6, 0, 1, 2, 3, 3, 4, 1, 2, 3, 3, 3, 4, 4, 5, 5, 6, 8]),
 array([0, 1, 0, 5, 6, 0, 1, 2, 2, 3, 0, 1, 2, 2, 2, 3, 3, 4, 4, 5, 7, 8]),
 array([6, 0, 6, 4, 5, 6, 0, 1, 1, 2, 6, 0, 1, 1, 1, 2, 2, 3, 3, 4, 6, 7,
        8, 8, 8, 8])]

In [5]:
fishes_history = simulate_fishes(fishes, 80)
fishes_history[80]

array([6, 0, 5, ..., 8, 8, 8])

#### Part 1 Answer
Find a way to simulate lanternfish.  
**How many lanternfish would there be after 80 days?**

In [6]:
len(fishes_history[80])

358214

### Part 2

In [7]:
256 // 7, 256 % 7

(36, 4)

In [8]:
2 ** 36

68719476736

The list would be billions of items long.

☞ Use a histogram instead of a long list.

In [9]:
def count_fishes_of_age(fishes):
    fishes_of_age = []
    for i in range(9):
        fishes_of_age.append(np.count_nonzero(fishes == i))
    return fishes_of_age
    
count_fishes_of_age(fishes)

[0, 107, 45, 49, 49, 50, 0, 0, 0]

In [10]:
count_fishes_of_age(fishes_history[80])

[23483, 45967, 30452, 48818, 43197, 46006, 61930, 21980, 36381]

In [11]:
def simulate_fishes_by_age(initial_fishes, num_days):
    fishes_of_age = count_fishes_of_age(initial_fishes)
    history = [fishes_of_age]
    for i in range(num_days):
        fishes_today = history[i]
        num_spawns = fishes_today[0]
        fishes_tomorrow = fishes_today[1:] + [num_spawns]
        fishes_tomorrow[6] += num_spawns
        history.append(fishes_tomorrow)
    return history

example_history = simulate_fishes_by_age(np.array([3,4,3,1,2]), 256)
sum(example_history[256])

26984457539

#### Part 2 Answer
**How many lanternfish would there be after 256 days?**

In [12]:
fishes_history = simulate_fishes_by_age(fishes, 256)
sum(fishes_history[256])

1622533344325