# Advent of Code 2022
## [Day 9: Rope Bridge](https://adventofcode.com/2022/day/9)

In [1]:
get_ipython().ast_node_interactivity = 'all'

In [2]:
import aocd
input_data = aocd.get_data(year=2022, day=9).split("\n")
input_data[:5]

['L 2', 'D 2', 'R 2', 'U 1', 'L 1']

In [3]:
commands = [
    (line[0], int(line[2:])) for line in input_data
]
commands[:5]

[('L', 2), ('D', 2), ('R', 2), ('U', 1), ('L', 1)]

### Part 1

In [4]:
import numpy as np

In [5]:
directions = {
    'U': np.array([-1, 0]),
    'D': np.array([ 1, 0]),
    'R': np.array([ 0, 1]),
    'L': np.array([ 0,-1]),
}

In [6]:
head = np.array([2,-2])
tail = np.array([0,0])
head - tail
np.abs(head - tail).max() > 1
np.abs(head - tail).sum() > 2

array([ 2, -2])

True

True

In [7]:
head = np.array([0,0])
tail = np.array([0,0])
tail_visited = set()

for command in commands:
    d = directions[command[0]]
    steps = command[1]
    for _ in range(steps):
        head += d
        # same row or col
        if np.abs(head - tail).max() > 1 or np.abs(head - tail).sum() > 2:
            tail += (head - tail).clip(-1,1)
        tail_visited.add(tuple(tail))
        
head, tail

(array([ -82, -400]), array([ -83, -400]))

#### Part 1 Answer
Simulate your complete hypothetical series of motions.  
**How many positions does the tail of the rope visit at least once?**

In [8]:
len(tail_visited)

5513

### Part 2

In [9]:
def pull_link(head, tail):
    if np.abs(head - tail).max() > 1 or np.abs(head - tail).sum() > 2:
        tail += (head - tail).clip(-1,1)

In [10]:
links = [np.array([0,0]) for _ in range(10)]
links[0] = np.array([5,5])

for i in range(1, 9):
    pull_link(links[i-1], links[i])
    
links

[array([5, 5]),
 array([1, 1]),
 array([0, 0]),
 array([0, 0]),
 array([0, 0]),
 array([0, 0]),
 array([0, 0]),
 array([0, 0]),
 array([0, 0]),
 array([0, 0])]

In [11]:
links = [np.array([0,0]) for _ in range(10)]
tail_visited = set()
for command in commands:
    d = directions[command[0]]
    steps = command[1]
    for _ in range(steps):
        links[0] += d
        for i in range(1, 10):
            pull_link(links[i-1], links[i])
        tail_visited.add(tuple(links[9]))
links

[array([ -82, -400]),
 array([ -83, -400]),
 array([ -84, -400]),
 array([ -85, -400]),
 array([ -86, -399]),
 array([ -86, -399]),
 array([ -86, -400]),
 array([ -86, -401]),
 array([ -86, -402]),
 array([ -86, -403])]

#### Part 2 Answer

Simulate your complete series of motions on a larger rope with ten knots.  
**How many positions does the tail of the rope visit at least once?**

In [12]:
len(tail_visited)

2427