# Advent of Code 2021
## [Day 11: Dumbo Octopus](https://adventofcode.com/2021/day/11)

### Part 1

In [1]:
import numpy as np
import html
html_formatter = get_ipython().display_formatter.formatters['text/html']

def ndarray_to_html(a):
    if a.dtype == np.dtype('bool'):
        a = a.astype(int)
    return "<pre>{}</pre>".format(html.escape(str(a)))

html_formatter.for_type(np.ndarray, ndarray_to_html)
pass

In [2]:
with open("input.txt") as f:
    input_data = np.array([
        list(line.strip()) for line in f.readlines()
    ], dtype=int)
input_data

array([[8, 5, 7, 7, 2, 4, 5, 5, 4, 7],
       [1, 6, 5, 4, 3, 3, 3, 6, 5, 3],
       [5, 3, 6, 5, 6, 3, 3, 7, 8, 5],
       [1, 3, 3, 3, 2, 4, 3, 2, 2, 6],
       [4, 2, 7, 2, 3, 8, 5, 1, 6, 5],
       [5, 6, 8, 8, 3, 2, 8, 4, 3, 2],
       [3, 1, 7, 5, 6, 3, 4, 2, 5, 4],
       [6, 7, 7, 5, 1, 4, 2, 2, 2, 7],
       [6, 1, 5, 2, 7, 2, 1, 4, 1, 5],
       [2, 6, 7, 8, 2, 2, 7, 3, 2, 5]])

In [3]:
test_data = np.array([list(line) for line in [
    '5483143223',
    '2745854711',
    '5264556173',
    '6141336146',
    '6357385478',
    '4167524645',
    '2176841721',
    '6882881134',
    '4846848554',
    '5283751526'
]], dtype=int)
test_data

array([[5, 4, 8, 3, 1, 4, 3, 2, 2, 3],
       [2, 7, 4, 5, 8, 5, 4, 7, 1, 1],
       [5, 2, 6, 4, 5, 5, 6, 1, 7, 3],
       [6, 1, 4, 1, 3, 3, 6, 1, 4, 6],
       [6, 3, 5, 7, 3, 8, 5, 4, 7, 8],
       [4, 1, 6, 7, 5, 2, 4, 6, 4, 5],
       [2, 1, 7, 6, 8, 4, 1, 7, 2, 1],
       [6, 8, 8, 2, 8, 8, 1, 1, 3, 4],
       [4, 8, 4, 6, 8, 4, 8, 5, 5, 4],
       [5, 2, 8, 3, 7, 5, 1, 5, 2, 6]])

In [4]:
flash = np.array([
    [1,1,1],
    [1,0,1],
    [1,1,1]
], dtype=bool)
flash

array([[ True,  True,  True],
       [ True, False,  True],
       [ True,  True,  True]])

In [5]:
def step(energy):
    energy = np.pad(energy, 1, constant_values=-127)
    energy += 1
    has_flashed = np.zeros_like(energy, dtype=bool)
    flashes = (energy > 9) & ~has_flashed
    while flashes.sum() > 0:
        has_flashed = has_flashed | flashes
        for i, j in np.array(np.where(flashes)).T:
            energy[i-1:i+2, j-1:j+2] += flash
        flashes = (energy > 9) & ~has_flashed
    energy[has_flashed] = 0
    num_flashes = has_flashed.sum()
    
    return energy[1:-1, 1:-1], num_flashes
step(test_data+1)

(array([[8, 8, 0, 7, 4, 7, 6, 5, 5, 5],
        [5, 0, 8, 9, 0, 8, 7, 0, 5, 4],
        [8, 5, 9, 7, 8, 8, 9, 6, 0, 8],
        [8, 4, 8, 5, 7, 6, 9, 6, 0, 0],
        [8, 7, 0, 0, 9, 0, 8, 8, 0, 0],
        [6, 6, 0, 0, 0, 8, 8, 9, 8, 9],
        [6, 8, 0, 0, 0, 0, 5, 9, 4, 3],
        [0, 0, 0, 0, 0, 0, 7, 4, 5, 6],
        [9, 0, 0, 0, 0, 0, 0, 8, 7, 6],
        [8, 7, 0, 0, 0, 0, 6, 8, 4, 8]]),
 35)

In [6]:
def iterate_steps(energy, num_steps):
    total_flashes = 0
    for _ in range(num_steps):
        energy, new_flashes = step(energy)
        total_flashes += new_flashes
    return energy, total_flashes
iterate_steps(test_data, 100)

(array([[0, 3, 9, 7, 6, 6, 6, 8, 6, 6],
        [0, 7, 4, 9, 7, 6, 6, 9, 1, 8],
        [0, 0, 5, 3, 9, 7, 6, 9, 3, 3],
        [0, 0, 0, 4, 2, 9, 7, 8, 2, 2],
        [0, 0, 0, 4, 2, 2, 9, 8, 9, 2],
        [0, 0, 5, 3, 2, 2, 2, 8, 7, 7],
        [0, 5, 3, 2, 2, 2, 2, 9, 6, 6],
        [9, 3, 2, 2, 2, 2, 8, 9, 6, 6],
        [7, 9, 2, 2, 2, 8, 6, 8, 6, 6],
        [6, 7, 8, 9, 9, 9, 8, 7, 6, 6]]),
 1656)

#### Part 1 Answer
Given the starting energy levels of the dumbo octopuses in your cavern, simulate 100 steps.  
**How many total flashes are there after 100 steps?**

In [7]:
iterate_steps(input_data, 100)

(array([[1, 7, 9, 8, 9, 7, 7, 7, 8, 0],
        [8, 1, 4, 4, 4, 0, 0, 0, 0, 0],
        [1, 1, 7, 7, 0, 0, 0, 0, 0, 0],
        [1, 1, 3, 0, 0, 0, 0, 0, 0, 0],
        [1, 1, 4, 0, 0, 0, 0, 0, 0, 5],
        [1, 2, 5, 0, 0, 0, 0, 0, 5, 3],
        [1, 3, 0, 0, 0, 0, 0, 5, 3, 2],
        [6, 8, 0, 0, 0, 0, 5, 3, 2, 2],
        [4, 5, 7, 0, 0, 5, 3, 2, 2, 8],
        [4, 4, 5, 7, 4, 3, 2, 2, 8, 6]]),
 1702)

### Part 2

In [8]:
def find_simultanous(energy, num_steps):
    total_flashes = 0
    for i in range(num_steps):
        energy, new_flashes = step(energy)
        total_flashes += new_flashes
        if np.count_nonzero(energy) == 0:
            return energy, i+1
    return energy, total_flashes
find_simultanous(test_data, 1000)

(array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]),
 195)

#### Part 2 Answer
If you can calculate the exact moments when the octopuses will all flash simultaneously, you should be able to navigate through the cavern.  
**What is the first step during which all octopuses flash?**

In [9]:
find_simultanous(input_data, 1000)

(array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]),
 251)