In [73]:
import aocd
import numpy as np
import re

In [66]:
inputs = aocd.get_data(day=4, year=2021).split("\n")
inputs

['12,28,0,63,26,38,64,17,74,67,51,44,77,32,6,10,52,47,61,46,50,29,15,1,39,37,13,66,45,8,68,96,53,40,76,72,21,93,16,83,62,48,11,9,20,36,91,19,5,42,99,84,4,95,92,89,7,71,34,35,55,22,59,18,49,14,54,85,82,58,24,73,31,97,69,43,65,27,81,56,87,70,33,88,60,2,75,90,57,94,23,30,78,80,41,3,98,25,79,86',
 '',
 '50 79 88 34  0',
 '56 46  5 17 31',
 '29  6 38 78 68',
 '75 57 15 44 83',
 '89 45 43 85 72',
 '',
 '29  8 56 15 33',
 ' 7 14 51 88 67',
 '91 32 62 18 73',
 '53 63 49 34 46',
 '70 25 77 87 31',
 '',
 '38 92 26 65 77',
 '59 39  4 57 16',
 '91 45 35 36  2',
 '34 40 89  8 62',
 '96 28 31 88 33',
 '',
 '93 96 73 40 13',
 '57 59 88 32 78',
 '48 72 23 42 62',
 '41  7 85 84 44',
 '95 91 52 61  8',
 '',
 '23 42 58 38 46',
 '41 91 92 81 68',
 '12 51 50 64 71',
 '32 13 55 44 35',
 '74  4 40 15 77',
 '',
 '19 79  7 65 77',
 '56 98 93 86 87',
 ' 5 68  8  2 49',
 '83 45 74 92  6',
 '46 88 33 58 28',
 '',
 '79 82 12 77 30',
 '68  6 70 23 80',
 '24 85 69 91 90',
 '57 15  1 52  8',
 '43 26 44 17 53',
 '',
 

In [49]:
called_numbers = np.array(inputs[0].split(','), dtype=int)
called_numbers

array([12, 28,  0, 63, 26, 38, 64, 17, 74, 67, 51, 44, 77, 32,  6, 10, 52,
       47, 61, 46, 50, 29, 15,  1, 39, 37, 13, 66, 45,  8, 68, 96, 53, 40,
       76, 72, 21, 93, 16, 83, 62, 48, 11,  9, 20, 36, 91, 19,  5, 42, 99,
       84,  4, 95, 92, 89,  7, 71, 34, 35, 55, 22, 59, 18, 49, 14, 54, 85,
       82, 58, 24, 73, 31, 97, 69, 43, 65, 27, 81, 56, 87, 70, 33, 88, 60,
        2, 75, 90, 57, 94, 23, 30, 78, 80, 41,  3, 98, 25, 79, 86])

In [114]:
def load_boards():
    boards = []
    for i in range(2, len(inputs), 6):
        rows = [row.strip().replace('  ', ' ').split(' ') for row in inputs[i:i+5]]
        board = np.array(rows, dtype=int)
        boards.append(board)
    boards = np.array(boards)
    return boards
boards = load_boards()

In [107]:
def is_winner(board):
    matches = board < 0
    for row in matches:
        if row.sum() == 5:
            return True
    for col in matches.T:
        if col.sum() == 5:
            return True
    return False

In [144]:
def run_bingo(boards):
    matches = np.zeros_like(boards, dtype='int8')
    for num in called_numbers:
        matches[boards == num] = -1
        for i in range(len(boards)):
            board = boards[i]
            match = matches[i]
            if is_winner(match):
                print(board)
                sum_unmarked = board[match < 0].sum()
                return sum_unmarked * num
run_bingo(load_boards())

[[99 19 74  0  9]
 [59 92 67 82 69]
 [72 46 63 51 77]
 [ 2 45 66 28 12]
 [93 38 15 64 27]]


39666

In [117]:
def run_bingo(boards):
    for num in called_numbers:
        # print(f"called {num}")
        for board in boards:
            board[board == num] = -num - 1
            if is_winner(board):
                sum_unmarked = board[board >= 0].sum()
                print(board)
                return(sum_unmarked * num)
run_bingo(load_boards())

[[ 99  19 -75  -1   9]
 [ 59  92 -68  82  69]
 [ 72 -47 -64 -52 -78]
 [  2  45 -67 -29 -13]
 [ 93 -39 -16 -65  27]]


44088

In [131]:
def run_bingo_lose(boards):
    num_winners = 0
    for num in called_numbers:
        # print(f"called {num}")
        boards[boards == num] = -num - 1
        for board in boards:
            if is_winner(board):
                num_winners += 1
                if num_winners == len(boards):
                    sum_unmarked = board[board >= 0].sum()
                    print(board)
                    return(sum_unmarked * num)
                board[board != 999] = 999
                
run_bingo_lose(load_boards())

[[  3 -14 -59 -51 -18]
 [ -5  78 -70 -17 -39]
 [-92  -3  23 -22 -52]
 [-50  79 -32 -98 -91]
 [-38 -47 -13  80 -29]]


23670